# Generated by Django 4.0.5 on 2022-06-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0006_rename_post_rated_rating_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='content_average',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='design_average',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='usability_average',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
